### ISSUE TITLE
IDEA 2024.2 Support

### ISSUE THREAD

**Issue by KasumiNova** [eigenraven/MinecraftDev#5]
### Minecraft Development for IntelliJ plugin version

2024.1-1.7.5-RFG

### Description of the feature request

IDEA 2024.2 does not support the current latest version of the plugin.

**Comment by komimoe** [comment]
https://github.com/eigenraven/MinecraftDev/releases/tag/RFG-1.7.5-2024.2

**Comment by komimoe** [comment]
《ECO 实验室摸鱼部》
